### ISSUE TITLE
know  the  number of active  connexion 

### ISSUE THREAD

**Issue by zoat** [ExampleDriven/spring-boot-grcp-example#5]
I want to know the number of active  connection
In  my previous work   I  use
 Server server = ServerBuilder.forPort(5000)
          .addService(new RetrieveServiceImpl()).addTransportFilter(filter).build();

and filter is

final AtomicInteger terminationCallbackCalled = new AtomicInteger(0);
        final AtomicInteger readyCallbackCalled = new AtomicInteger(0);
        final AtomicReference<Attributes> filter1TerminationCallbackArgument = new AtomicReference<>();
 ServerTransportFilter filter = new ServerTransportFilter(){

            @Override
            public Attributes transportReady(Attributes transportAttrs) {

                readyCallbackCalled.incrementAndGet();

                System.out.println(readyCallbackCalled);
                return super.transportReady(transportAttrs);

            }

            @Override
            public void transportTerminated(Attributes transportAttrs) {
                terminationCallbackCalled.incrementAndGet();
                System.out.println(terminationCallbackCalled);
                filter1TerminationCallbackArgument.set(transportAttrs);

                System.out.println(readyCallbackCalled);

                //super.transportTerminated(transportAttrs);
            }
        };

thanks

**Comment by szantopeter** [comment]
If you are lucky then you just register your filter as a @Component and the framework pick it up. If not then read the source code or documentation of the GRPC starter
